#Multi Stage Pipeline 
# Stage 1 - Build Phase - compilation of app code and DB code along with Terraform validate job
# Stage 2 - Deployment Phase - Deploy the infra code and the DB and App code in Dev Environment

name: $(Rev:r)

variables:
  - name: tf_path
    value: '$(build.sourcesdirectory)'
  - name: Azure_Service_ConnectionName
    value: 'InfaCode'
  - name: Azure_ResourceGroupName
    value: 'InsightApp'
  - name: Azure_StorageAccountName
    value: 'demostatefiles1'
  - name: Azure_ContainerName
    value: 'techslate'

pool:
  vmImage: 'windows-latest'

parameters:
 - name: rings
   displayName: rings
   type: object
   default:
      - name: "dev" 
     # - name: "qa"
     # - name: "prod"

stages:
- stage: build
  jobs:
    - job: Compile
      displayName: 'Compile App code and DB code'
      steps:
      - task: Maven@4
        displayName: 'Maven pom.xml'
        inputs:
          options: '-DskipITs --settings ./maven/settings.xml'

      - task: CopyFiles@2
        displayName: 'Copy Files'
        inputs:
          SourceFolder: '$(build.sourcesdirectory)'
          Contents: |
            **/target/*.war
            *.sql
          TargetFolder: '$(build.artifactstagingdirectory)'
     

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.sourcesdirectory)/terraform'
          ArtifactName: 'drop/terraform'
          publishLocation: 'Container'

# for loop to run the terraform steps for different enviroements based on the no of environments mention in ringName Parameters
    - ${{each ring in parameters.rings}}:
      - job: Terraform_Step_${{ring.name}}
        displayName: 'validate Infra code'
        steps:
          - template: template/terraform_steps.yml
            parameters:
              ringName: ${{ring.name}}
              tf_path: $(tf_path)
              Azure_Service_ConnectionName: $(Azure_Service_ConnectionName)
              Azure_ResourceGroupName: $(Azure_ResourceGroupName)
              Azure_StorageAccountName: $(Azure_StorageAccountName)
              Azure_ContainerName: $(Azure_ContainerName)

#Dynamic step to create 'N' no of Deployments stages based on Number of enviroments mentioned in ringName parameters
- ${{each ring in parameters.rings}}:
      - template: template/code_deployment.yml
        parameters:
          ringName: ${{ring.name}}
          Azure_Service_ConnectionName: $(Azure_Service_ConnectionName)
          Azure_ResourceGroupName: $(Azure_ResourceGroupName)
          Azure_StorageAccountName: $(Azure_StorageAccountName)
          Azure_ContainerName: $(Azure_ContainerName)
          DB_UserName: $(DB_UserName)
          DB_Password: $(DB_Password)
          
